### ISSUE TITLE
UI to manage downloading crawling and depth/breadth - {multiple subtasks}

### ISSUE THREAD

**Issue by mitra42** [internetarchive/dweb-mirror#140]
- [ ] See TODO-UXLOCAL in code
- [ ] On item, should indicate "downloaded all|details" rather than crawlinh
- [ ] On item, drop down should say Downloaded rather than Download if done and "Dont download" 
- [ ] Note - movie can display Details without Downloading it.
- [ ] Handle Search - more complex

**Comment by mitra42** [comment]
Straw person UI - for Item 
* Text says "downloaded xx/yy
* download xxMb
* download all files yy Mb

This does once add check button that copies to crawl

**Comment by mitra42** [comment]
Collection & Crawl 
* downloaded xx members yyMb
* download tiles ~yyMb
* download n items ~zzMb
If <1000 then 3 10 30 100 300 all
If > 1000 then 10 100 1000 10000 100000 all

**Comment by mitra42** [comment]
- [ ] Write path is ....
- mirrorHttp admin/crawl/setconfig/IDENTIFIER/LEVEL?q=
  - [ ] add rows OR replace with a new command
- [ ]  MirrorConfig.writeUserTaskLevel - extend to support search number

**Comment by mitra42** [comment]
[ ] Crawl specifier
- [ ] Add checkbox to UI
- [ ] Calls admin/crawl/setconfig.... (see above)

**Comment by mitra42** [comment]
] Adding one time to crawl - 
- mirrorHttp admin/crawl/add ? identifier=xxx query=xxx search=xxx ..... 
- CrawlManager.add needs:
  - [x] level: default to 'details'
  - [ ] rows: - then adds search: {rows, level}
    - [ ] test failing [http://localhost:4244/admin/crawl/add?identifier=prelinger&rows=3]

**Comment by mitra42** [comment]
Basically done - any oddities can be posted as new issues
