### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by mitra42** [internetarchive/dweb-mirror#232]
- [x] Merge INSTALLATION-* into INSTALLATION-work
- [x] Test on RPI4+-NOOBS
- [x] Test on OrangePi
- [x] Merge back to other platforms
- [x] Upgrade - see #219 
- [x] Fix restart instructions #196
