### ISSUE TITLE
Package dependency warnings {META}

### ISSUE THREAD

**Issue by mitra42** [internetarchive/dweb-mirror#234]
THis task is for an ongoing list of warnings during yarn upgrade and install

**Comment by mitra42** [comment]
- [ ] Gun > text-encoding@0.7.0 no longer maintained See [gun#788](https://github.com/amark/gun/issues/788)
- [ ] warning @internetarchive/dweb-objects > @internetarchive/dweb-transports > ipfs > boom@7.3.0: This module has moved and is now available at @hapi/boom....
- [ ] warning @internetarchive/dweb-objects > @internetarchive/dweb-transports > ipfs > hapi@18.1.0: This module has moved and is now available at @hapi/hapi. ...
- [ ] warning @internetarchive/dweb-objects > @internetarchive/dweb-transports > ipfs > joi@14.3.1: This module has moved and is now available at @hapi/joi. 
- [ ] warning @internetarchive/dweb-objects > @internetarchive/dweb-transports > gun > emailjs > emailjs-mime-codec > text-encoding@0.7.0: no longer maintained
- [ ] warning @internetarchive/dweb-objects > @internetarchive/dweb-transports > wolkjs > @trust/webcrypto > text-encoding@0.6.4: no longer maintained
- [ ] warning "@internetarchive/dweb-archive > @babel/preset-react@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0"

**Comment by mitra42** [comment]
Warnings via IPFS dependency
Reported at https://github.com/ipfs/js-ipfs/issues/2347

- [ ] warning @internetarchive/dweb-objects > @internetarchive/dweb-transports > ipfs > boom@7.3.0: This module has moved and is now available at @hapi/boom....
- [ ] warning @internetarchive/dweb-objects > @internetarchive/dweb-transports > ipfs > hapi@18.1.0: This module has moved and is now available at @hapi/hapi. ...
- [ ] warning @internetarchive/dweb-objects > @internetarchive/dweb-transports > ipfs > joi@14.3.1: This module has moved and is now available at @hapi/joi.

**Comment by mitra42** [comment]
Wolk warning reported at https://github.com/wolkdb/wolkjs/issues/81
- [ ] warning @internetarchive/dweb-objects > @internetarchive/dweb-transports > wolkjs > @trust/webcrypto > text-encoding@0.6.4: no longer maintained

**Comment by mitra42** [comment]
Gun warning reported at  [gun#788](https://github.com/amark/gun/issues/788)
- [ ] Gun > text-encoding@0.7.0 no longer maintained

**Comment by mitra42** [comment]
- [ ] Emailjs warning reported at [emailjs-mime-codec#34](https://github.com/emailjs/emailjs-mime-codec/issues/34) which appears to be unmaintained.
```
warning @internetarchive/dweb-objects > @internetarchive/dweb-transports > gun > emailjs > emailjs-mime-codec > text-encoding@0.7.0: no longer maintained
```

**Comment by mitra42** [comment]
Babel peer dependencies
- [ ] warning "@internetarchive/dweb-archive > @babel/preset-react@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0"
- [ ] warning "@internetarchive/dweb-archive > @babel/preset-env@7.5.5" has unmet peer dependency "@babel/core@^7.0.0-0".

**Comment by mitra42** [comment]
- [ ] Webrtc peer dependency
warning "wrtc@0.2.1" is missing a bundled dependency "node-pre-gyp". This should be reported to the package maintainer.

**Comment by mitra42** [comment]
The IPFS warnings are fixed except in their sub-dependencies
```
warning @internetarchive/dweb-objects > @internetarchive/dweb-transports > ipfs > hapi-pino > @hapi/hoek@6.2.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
```
Reported on 
https://github.com/pinojs/hapi-pino/issues/82

and 
```
warning @internetarchive/dweb-objects > @internetarchive/dweb-transports > ipfs > @hapi/joi > @hapi/hoek@6.2.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
```
which should fix itself as @hapi/joi has a 16.0.1 which points at a later @hapi/hoek

**Comment by mitra42** [comment]
For tracking purposes the following warnings are to be expected .... 
- ` "warning package.json: No license field"` is because we do a `yarn add` to create the package.json automatically
- ` "info fsevents@1.2.9: The platform "linux" is incompatible with this module.",` is because this is a browser specific optional dependency.
