### ISSUE TITLE
Epub option to bookreading - see if there is a reader (maybe ask Mark)

### ISSUE THREAD

**Issue by mitra42** [internetarchive/dweb-mirror#240]
Add EPub option to bookreading (ask Mek if there is a reader)

**Comment by mitra42** [comment]
- [ ] See slack notes from Mek in email 
- [ ] Find a good public epub example 
- [ ] Find a good OpenLibrary epub example
- [ ] Look on archive.org at example, see how download link integrated
   - [ ] Fix https://github.com/internetarchive/dweb-archive/issues/139 at same time
   - [ ] Integrate straightforward epub download into dweb-archive
   - [ ] Write heuristic that decides if have an epub
- [ ] Make crawler grab epub
- [ ] How to display epub in bookreader or as alternative 
- [ ] Think thru any issues related to WorldReader https://github.com/internetarchive/dweb-mirror/issues/245 
- [ ] Check notebook pg 60 for any other notes

**Comment by mitra42** [comment]
https://archive.org/download/LasCrucesSobreElAguaJoaquinGallegosLara/Las%20cruces%20sobre%20el%20agua%20-%20Joaquin%20Gallegos%20Lara.epub working one 
https://archive.org/download/The_Woodworkers_Studio_Handbook_by_Jim_Whitman/The_Woodworkers_Studio_Handbook_by_Jim_Whitman.epub
https://archive.org/download/ArtOfCommunitySecondEdition/Art_of_Community_Second_Edition.epub

**Comment by mitra42** [comment]
Brenton said: Yeah, we have no epub compatibility in BookReader. If we wanted to add that functionality to our site (whether in the context of BookReader or not), we could use ReadiumJS. and then We haven’t so far really researched integration possibilities, but if it’s easy..

**Comment by mitra42** [comment]
I can't figure out Readium.js never mind how to integrate it with Bookreader, an alternative would be epub.js  https://github.com/futurepress/epubjs-reader which from view-source:https://futurepress.github.io/epubjs-reader/index.html looks much simpler as a stand alone e-reader

**Comment by mitra42** [comment]
Working on download link ... 
   - [x] Fix https://github.com/internetarchive/dweb-archive/issues/139 at same time
   - [ ] Integrate straightforward epub download into dweb-archive
   - [ ] Write heuristic that decides if have an epub
   - [ ] In DownloadOptions.render Add formulaic epub and kindle (.mobi) files if matches test
   - [ ] integrate reachable into test at same time
   - [ ] Resort if added anything

**Comment by mitra42** [comment]
- [ ] DM - allow epubs to download: e.g. http://localhost:4244/arc/archive.org/metadata/ArtOfCommunitySecondEdition/ArtOfCommunitySecondEdition.epub fails 
  - [ ] Looks like http://localhost:4244/arc/archive.org/metadata/ArtOfCommunitySecondEdition fails on DM
  - [ ] Bad follow on to this failure - crashes with multiple lock errors and hten a `throw new ReadError('get() requires a key argument')`
    - Why is it crashing after lock failures probably hits count out
    - Why is lock getting set ?
       - doing a get with no value - now catch that and throw error
       - doing a hashstore lookup even with no digest - fixed 
    - [ ] Why is it even doing a fetch of  https://dweb.me/arc/archive.org/metadata/ArtOfCommunitySecondEdition/ArtOfCommunitySecondEdition.epub  
    - [ ] Why is that URL failing on gateway

STR
rm /Volumes/Transcend/archiveorg/.hashStore.sha1.relfilepath/LOCK
curl -o/tmp/foo http://localhost:4244/arc/archive.org/metadata/ArtOfCommunitySecondEdition

**Comment by mitra42** [comment]
- [ ] DM - allow epubs to download: e.g. http://localhost:4244/arc/archive.org/download/ArtOfCommunitySecondEdition/ArtOfCommunitySecondEdition.epub

**Comment by mitra42** [comment]
Plan ... 
- [ ] divert DM so call to https://dweb.me/arc/archive.org/download/ArtOfCommunitySecondEdition/ArtOfCommunitySecondEdition.epub replaced by call to https://archive.org/download/ArtOfCommunitySecondEdition/ArtOfCommunitySecondEdition.epub
- [ ] make sure error returned
- [ ] work on Jira so it gets fixed

**Comment by mitra42** [comment]
GOOD EPUB DOWNLOAD
- [localhost](http://localhost:4244/arc/archive.org/download/The_Woodworkers_Studio_Handbook_by_Jim_Whitman/The_Woodworkers_Studio_Handbook_by_Jim_Whitman.epub) 
goes to [dweb.me](https://dweb.me/arc/archive.org/download/The_Woodworkers_Studio_Handbook_by_Jim_Whitman/The_Woodworkers_Studio_Handbook_by_Jim_Whitman.epub)
which fails. 
Should go to: [archive.org](https://archive.org/download/The_Woodworkers_Studio_Handbook_by_Jim_Whitman/The_Woodworkers_Studio_Handbook_by_Jim_Whitman.epub)

**Comment by mitra42** [comment]
Displaying in UI
- [x] Added to dweb-mirror#epub and dweb-archive#epub 
- [ ] need link against EPUB download for viewing it
- [ ] merge into master

**Comment by mitra42** [comment]
- [ ]Figure out algorithm for a) its an epub and b) doesnt require lending ... 
See chat with db48x. 
* Rule  texts + file:format=Abbyy GZ
* Rule member of xxx means can’t lend

https://github.com/internetarchive/dweb-mirror/issues/240
|---|Epub|Access|Issues|
|ArtOfCommunitySecondEdition|y|y|Getting not allowed - retest|
|potbouille02zola|
