### ISSUE TITLE
MediaWiki - top level meta task

### ISSUE THREAD

**Issue by mitra42** [internetarchive/dweb-mirror#286]
The basic idea is to 
* port the Palm Leaf mediawiki instance at [palmleaf.org](http://palmleaf.org/wiki/Main_Page) to small boxes (Nuc, RPI) 
* make it available alongside dweb-mirror 
* trial in a high school in Bali with minimal internet connectivity 

This is a meta-task for this sub-project until/unless the project gets its own tracking space.

**Comment by mitra42** [comment]
#### Porting to Nuc
This is mostly done and I appear to have a fully functioning wiki - a few mistakes were made along the way, but next install should be smoother. 

- [ ] Copy installation directions from Evernote to somewhere shareable (probably on the repo), will do this as I repeat the port for the RPI

**Comment by mitra42** [comment]
#### Local integration with dweb-mirror / dweb-archive
Goal to make it so links in the mediawiki go to the local dweb-mirror rather than back to archive.org
- [ ] figure out how to configure this
  - [ ] hypothesis - a variable in LocalSettings.php called mirror (so same as on dweb-mirror)
  - [ ] will need if/then around links 
  - [ ] Search all the extensions for links 
    - [ ] ArchiveLeaf
    - [ ] ArchiveMirador
    - [ ] ArchiveOrgAuth - but careful, actually want to authenticate to archive.org

**Comment by mitra42** [comment]
#### Upload
Hard, and for later, but figure out how to send changes back 
- maybe it could be as easy as in the Transcriber ?
- maybe push changes to Archive.org items or some companion to it 
- maybe just edit when online to archive.org (at least in short run)

**Comment by mitra42** [comment]
#### Updating
- [ ] how to update each wiki as changes happen on archive.org or palmleaf.org or are pushed back from other remotes

- [ ] Need an export process from palmleaf.org
- [ ] Need a way to track new Palmleaf items via dweb-mirror
- [ ] Need an incremental import process

**Comment by mitra42** [comment]
#### Port to Raspberry Pi
- [ ] work through instructions on Evernote
- [ ] Update and transcribe those instructions and add to repo

**Comment by mitra42** [comment]
#### Installer

See dweb-mirror/install-mediawiki.sh 
Mostly textual instructions 
- [ ] try on fresh RPI

**Comment by mitra42** [comment]
#### Links dweb-archive -> mediawiki
- [ ] Details page links

**Comment by mitra42** [comment]
#### Image size
I thought I was seeing multiple sizes of images, need to check when back online
David says should be a 400px and a full size only.

**Comment by mitra42** [comment]
#### Minor bugs probably transient 
- [ ] http://192.168.0.14/mediawiki
Random goes to http://192.168.0.14/wiki/Special:Random and loads a page
then on page that comes up 'Random' goes to same place but doesn't load.

**Comment by mitra42** [comment]
#### update_ia_item.py 
We are still missing  /home/davidk/script/update_ia_item.py.
[] Ask David for it, its refered to I think in ${LOCALSETTINGS}

**Comment by mitra42** [comment]
- [ ] One image failing it appears on the kbd when editing
https://palmleaf.org/transcriber/static/media/zwnj.0da8f3f5.svg works
https://192.168.0.14/transcriber/static/media/zwnj.0da8f3f5.svg works fails
manifests as permission problem on that url
Asked David for his /etc/apache2/conf-available/mediawiki.conf
