### ISSUE TITLE
Dweb.me dependency: BTIH Seeder and Tracker

### ISSUE THREAD

**Issue by mitra42** [internetarchive/dweb-mirror#292]
(Part of #242)
- [x] Changes to dweb-torrent to support /btih/xxxx
- [x] Push to k8
- test
  - [x] https://www-dweb-torrent.dev.archive.org/commute opens in WT but just the torrent file 
  - [x] https://www-dweb-torrent.dev.archive.org/download/commute/commute_archive.torrent 
  - [x] http://www-dweb-torrent.dev.archive.org/btih/7e849a0f2c0e5f9ea6ab72827e7690406904b010
- [x] Maybe replace URL in Tracker, but prob not needed 
  - In dweb-transport.seeder-config.json.validateUrl 
  - "https://archive.org/advancedsearch.php?fl=identifier,btih&output=json&rows=1&q=btih:"
- [x] Put Seeder in own repo
  - [x] need to figure out port opening with Tracey
- [x] Put Tracker in own repo
  - [x] need to figure out port opening with Tracey and how it finds Seeder by IP address (sin seeder-config.json)
- [ ] Make everything use new tracker:
  - [x] Replace URL in Seeder with https://www-dweb-cors.dev.archive.org/btih/xxxx
  - [x] munge_torrent
  - [x] Check dweb-cors uses munge_torrent config 
  - [x] check dweb-mirror uses munge_torrent config
  - [x] check dweb-archive uses munge_torrent config

**Comment by mitra42** [comment]
All working
